export default {
  name: 'project',
  title: 'Opportunities & Projects',
  type: 'document',
  fieldsets: [
    {
      name: 'projectInfo',
      title: '1. Información del Proyecto (Título y Ubicación)',
      options: { collapsible: true, collapsed: false },
    },
    {
      name: 'projectMedia',
      title: '2. Fotos del Proyecto (Subir Imágenes Antes y Después)',
      options: { collapsible: true, collapsed: false },
    },
    {
      name: 'projectDetails',
      title: '3. Detalles y Alcance de la Obra',
      options: { collapsible: true, collapsed: false },
    },
  ],
  fields: [
    {
      name: 'title',
      title: 'Project Opportunity Title',
      type: 'string',
      fieldset: 'projectInfo',
      description: 'e.g. Residential Builder Seeking Roofing Contractor',
      validation: (Rule: any) => Rule.required(),
    },
    {
      name: 'location',
      title: 'Location',
      type: 'string',
      fieldset: 'projectInfo',
      description: 'e.g. Austin, TX or Dallas, TX',
      validation: (Rule: any) => Rule.required(),
    },
    {
      name: 'scope',
      title: 'Project Scope Summary',
      type: 'string',
      fieldset: 'projectInfo',
      description: 'e.g. Architectural shingles, flashing & underlayment',
    },
    {
      name: 'beforeImage',
      title: 'Foto Antes / Obra en Progreso (Before Image)',
      type: 'image',
      fieldset: 'projectMedia',
      description: 'Haz clic en Upload para subir la foto del estado inicial o en progreso.',
      options: { hotspot: true },
    },
    {
      name: 'beforeImageAlt',
      title: 'Texto Alternativo (Antes)',
      type: 'string',
      fieldset: 'projectMedia',
    },
    {
      name: 'afterImage',
      title: 'Foto Después / Obra Terminada (After Image)',
      type: 'image',
      fieldset: 'projectMedia',
      description: 'Haz clic en Upload para subir la foto del proyecto finalizado.',
      options: { hotspot: true },
    },
    {
      name: 'afterImageAlt',
      title: 'Texto Alternativo (Después)',
      type: 'string',
      fieldset: 'projectMedia',
    },
    {
      name: 'challengeTitle',
      title: 'Slide Feature Title',
      type: 'string',
      fieldset: 'projectDetails',
      initialValue: 'Active Project Listings',
    },
    {
      name: 'challengeText',
      title: 'Slide Feature Description',
      type: 'text',
      fieldset: 'projectDetails',
      rows: 3,
    },
    {
      name: 'resultTitle',
      title: 'Result / Build Title',
      type: 'string',
      fieldset: 'projectDetails',
    },
    {
      name: 'resultText',
      title: 'Result Description & Trade Specs',
      type: 'text',
      fieldset: 'projectDetails',
      rows: 3,
    },
    {
      name: 'order',
      title: 'Display Order',
      type: 'number',
      initialValue: 1,
    },
  ],
};
