export default {
  name: 'siteSettings',
  title: 'Site Settings & Hero Copy',
  type: 'document',
  fieldsets: [
    {
      name: 'heroCopy',
      title: '1. Textos del Hero',
      options: { collapsible: true, collapsed: false },
    },
    {
      name: 'heroMedia',
      title: '2. Video del Hero (Subir Archivo o URL)',
      options: { collapsible: true, collapsed: false },
    },
    {
      name: 'howItWorksCopy',
      title: '3. Encabezados de "How It Works"',
      options: { collapsible: true, collapsed: false },
    },
    {
      name: 'contactInfo',
      title: '4. Información de Contacto',
      options: { collapsible: true, collapsed: false },
    },
    {
      name: 'integrations',
      title: '5. Integraciones y Formularios',
      options: { collapsible: true, collapsed: false },
    },
  ],
  fields: [
    {
      name: 'siteTitle',
      title: 'Site Title',
      type: 'string',
      initialValue: 'ContractorPro US',
    },
    {
      name: 'siteDescription',
      title: 'Site Description',
      type: 'text',
      rows: 2,
    },
    {
      name: 'heroTag',
      title: 'Hero Section Tag',
      type: 'string',
      fieldset: 'heroCopy',
      initialValue: 'SUBCONTRACTOR PROJECT ACCESS',
    },
    {
      name: 'heroTitle',
      title: 'Hero Main Headline',
      type: 'string',
      fieldset: 'heroCopy',
      initialValue: 'Connect With Construction Projects Looking for Subcontractors.',
    },
    {
      name: 'heroSubtitle',
      title: 'Hero Subtitle',
      type: 'text',
      fieldset: 'heroCopy',
      rows: 3,
    },
    {
      name: 'heroNotice',
      title: 'Hero Beta Notice',
      type: 'string',
      fieldset: 'heroCopy',
      initialValue: 'Founding contractors get free access while we launch the beta.',
    },
    {
      name: 'heroCtaText',
      title: 'Texto del Botón Early Access (Hero)',
      type: 'string',
      fieldset: 'heroCopy',
      initialValue: 'GET EARLY ACCESS',
      description: 'Texto del botón principal de llamada a la acción en el Hero.',
    },
    {
      name: 'heroCtaUrl',
      title: 'Enlace / URL de Redirección (Early Access)',
      type: 'string',
      fieldset: 'heroCopy',
      initialValue: '#contact',
      description: 'Destino al hacer clic en Early Access. Puede ser un ancla como #contact o un enlace externo completo como https://...',
    },
    {
      name: 'heroSecondaryCtaText',
      title: 'Texto del Botón Secundario (Hero)',
      type: 'string',
      fieldset: 'heroCopy',
      initialValue: 'How It Works?',
      description: 'Texto del botón secundario del Hero.',
    },
    {
      name: 'heroSecondaryCtaUrl',
      title: 'Enlace del Botón Secundario (Hero)',
      type: 'string',
      fieldset: 'heroCopy',
      initialValue: '#how-it-works',
      description: 'Destino del botón secundario (ej: #how-it-works o URL externa).',
    },
    {
      name: 'heroVideoFile',
      title: 'Subir Archivo de Video (.mp4 / .webm)',
      type: 'file',
      fieldset: 'heroMedia',
      description: 'Arrastra y suelta tu archivo de video aquí (MP4, WebM, etc.). Si subes un archivo, tendrá prioridad sobre la URL.',
      options: {
        accept: 'video/*',
      },
    },
    {
      name: 'heroVideoUrl',
      title: 'O Enlace URL del Video (Cloudinary, Vimeo, S3, etc.)',
      type: 'url',
      fieldset: 'heroMedia',
      description: 'Si prefieres usar un enlace externo directo, puedes ingresarlo aquí.',
      initialValue: 'https://res.cloudinary.com/dellp9a4z/video/upload/f_mp4,q_auto,w_1080/v1774623099/ik-video_esc1gl.mp4',
    },
    {
      name: 'heroVideoPoster',
      title: 'Hero Video Poster / Portada',
      type: 'image',
      fieldset: 'heroMedia',
      description: 'Imagen de portada que se muestra mientras el video comienza a reproducirse.',
      options: { hotspot: true },
    },
    {
      name: 'howItWorksTag',
      title: 'Tag / Etiqueta de la Sección',
      type: 'string',
      fieldset: 'howItWorksCopy',
      initialValue: 'HOW IT WORKS',
    },
    {
      name: 'howItWorksTitle',
      title: 'Título Principal de "How It Works"',
      type: 'string',
      fieldset: 'howItWorksCopy',
      initialValue: 'A simple path from joining the network to connecting with builders.',
    },
    {
      name: 'appLoginUrl',
      title: 'URL de Login de la App',
      type: 'url',
      description: 'Enlace del botón "Log In" del header (ej: https://www.app.contractorspro.us/)',
      initialValue: 'https://app.contractorspro.us/',
    },
    {
      name: 'contactSectionTag',
      title: 'Tag / Etiqueta de Contacto',
      type: 'string',
      fieldset: 'contactInfo',
      initialValue: 'FOUNDING ACCESS',
    },
    {
      name: 'contactSectionTitle',
      title: 'Título Principal de Contacto',
      type: 'string',
      fieldset: 'contactInfo',
      initialValue: 'Become a Founding Contractor.',
    },
    {
      name: 'contactSectionSubtitle',
      title: 'Subtítulo / Descripción de Contacto',
      type: 'text',
      rows: 2,
      fieldset: 'contactInfo',
      initialValue: "We're onboarding a limited group of subcontractors before public launch. Tell us about your services, crew capacity, and the compliance details builders typically need.",
    },
    {
      name: 'contactEmail',
      title: 'Support Email',
      type: 'string',
      fieldset: 'contactInfo',
      initialValue: 'contact@contractorspro.us',
    },
    {
      name: 'contactPhone',
      title: 'Support Telephone',
      type: 'string',
      fieldset: 'contactInfo',
      initialValue: '(888) 555-0199',
    },
    {
      name: 'hideContactForm',
      title: 'Ocultar Formulario de Contacto / Registro',
      type: 'boolean',
      fieldset: 'integrations',
      initialValue: false,
      description: 'Si se activa, el formulario de registro se ocultará en la página web manteniendo los datos de soporte.',
    },
    {
      name: 'hideContactSection',
      title: 'Ocultar Sección Completa de Contacto',
      type: 'boolean',
      fieldset: 'integrations',
      initialValue: false,
      description: 'Si se activa, se ocultará completamente toda la sección de contacto / founding access del sitio web.',
    },
    {
      name: 'googleScriptUrl',
      title: 'Google Apps Script Web App URL (Formulario a Google Sheets)',
      type: 'url',
      fieldset: 'integrations',
      description: 'URL generada al implementar el Apps Script como Aplicación Web (termina en /exec).',
    },
  ],
};

